delete from orderkern.BESTELLPOSITION;
delete  from orderkern.BESTELLUNG;
delete from orderkern.KUNDE;
delete from orderkern.RECHNUNG;
delete  from orderkern.VERKAUFSPREIS;
delete from orderkern.LIEFERANT;
delete from orderkern.WARE;
delete  from orderkern.HERSTELLER;
delete  from orderkern.WARENGRUPPE;
delete from orderkern.WARENKATEGORIE;
commit;